# ========== Profile ========== #
# avatar
avatar: /avatar/avatar.jpg
# author name
# author: Bean
# signature
signature: A true master is an eternal student.
# SNS (you can custom the order)
social:
  github: //github.com/beanya
  # wechat and qq should be a path of qr-code image
  wechat: /assets/WCQR.jpg
  email: isbean@qq.com
  qq: /assets/QQQR.jpg
  telegram: //t.me/beanya
  weibo: 
  zhihu: 
  douban: 
  facebook: 
  twitter: 
  instagram: 
  stack-overflow: 
  segmentFault: 
  juejin: 
  v2ex: 
  bilibili: 
  linkedin: 
  steam: 
  others: 
  rss: 
# friends
# friends:
#   friendA: //www.baidu.com
#   friendB: //www.google.com
#   friendC: 
about:
  enable: true
  # image: '/intro/about-bg.jpg'
  image: 'https://source.unsplash.com/random/2560x863'

# ========== Site ========== #
# title of the site (good for SEO)
SEO_title: Bean's Studio
# keywords for site (good for SEO)
SEO_keywords:
  - hexo
  - 'hexo-theme'
  - 'hexo-blog'
# main title shown in header image
main_title: Bean's Studio
# subtitle
subtitle: The world is not black or white, but a delicious shade of grey.
# site haeder image
# site_header_image: '/intro/index-bg.jpg'
site_header_image: 'https://source.unsplash.com/random/2560x863'
# post haeder image
post_header_image: '/intro/post-bg.jpg'
# 404 image
_404_image: '/intro/404-bg.jpg'

# ========== Search ========== #
algolia_search:
  enable: false
  hits:
    per_page: 10
  labels:
    input_placeholder: Search for Posts
    hits_empty: "We did not find any results for the search: ${query}"
    hits_stats: "${hits} results found in ${time} ms"

# ========== Comment ========== #
# Fill in the field to enable the corresponding comment plugin
# If you want to add other comment plugin, edit in "custom.ejs"
comment:
  # Livere  site: https://livere.com/
  livere_uid: 
  # Disqus  site: https://disqus.com/
  disqus_shortname: 
  # Gitment  site: https://github.com/imsun/gitment
  gitment_owner: 
  gitment_repo: 
  gitment_client_id: 
  gitment_client_secret: 
  # Youyan  site: http://www.uyan.cc/
  youyan_uid: 
  # Valine  site: https://valine.js.org/
  valine_appId: 
  valine_appKey: 
  valine_placeHolder: 

# ========== Analytics ========== #
# enable Busuanzi analytics
busuanzi: true
# fill in pv or uv
busuanzi_pv_or_uv: 'pv'
# custom analytic slogan, '${count}' is the analytic number, DO NOT modify it.
busuanzi_slug: 'PV: ${count} :)'
# Baidu analytics
baidu_analytics: 
# Google analytics
google_analytics: 
# CNZZ analytics
CNZZ_analytics: 

# ========== Others ========== #
# favicon
favicon: /assets/bean.ico
# truncate length of abstracts in index page (the default is 300, there will be no abstruct if you input 0)
truncate_length: 
# enable toc
toc: true
# word count & reading time
reading_info: true
# intro height (the default is 50 percents of the screen, you can input other number)
index_intro_height: 50
post_intro_height: 50
about_intro_height: 50
# copyright
copyright:
  enable: true
  # https://creativecommons.org/
  license: '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'

math:
  enable: true

  # Default(true) will load mathjax/katex script on demand
  # That is it only render those page who has 'mathjax: true' in Front Matter.
  # If you set it to false, it will load mathjax/katex srcipt EVERY PAGE.
  per_page: true

  # engine: mathjax
  engine: katex