# This is a basic workflow to help you get started with Actions
name: Hexo CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ source ]
  workflow_dispatch:
  
jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Fetch
        run: git fetch --all
      - name: Copy deploy.yml
        run: mv ./.github/workflows/deploy.yml ./public/.github/workflows/deploy.yml
      - name: Checkout
        run: git checkout origin/source
      - name: Hexo install
        run: npm install hexo -g
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: hexo g
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: master  # deploying branch
